version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: flask-react-board-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpswd"
      MYSQL_DATABASE: "flask_board"
      MYSQL_USER: "phspeed"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uphspeed", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: flask-react-board-backend-flask-container
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "flask-react-board-mysql-container"
      DB_PORT: "3306"
      DB_USER: "user"
      DB_PASSWORD: "password"
      DB_NAME: "flask_board"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    container_name: flask-react-board-frontend-react-container
    restart: always
    build: ./frontend
    ports:
      - "3100:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]
    depends_on:
      - backend

volumes:
  mysql_data:
